# Lab 2: Intro to NumPy and Stock Statistics

### Author: Eric Perry

## Part A: Intro to NumPy: (49 pts)

### Step A: (11 pts)

In [1]:
import numpy as np

In [2]:
# Add the cells for Step A
A1 = np.zeros((3, 4), dtype=int)
A1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [3]:
A1.shape

(3, 4)

In [4]:
A1.ndim

2

In [5]:
A1.dtype

dtype('int32')

In [6]:
A1.size

12

In [7]:
A2 = np.add(A1, 5)
A2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [8]:
A2[0][3] = 3
A2[1][2] = 1
A2[2][1] = 2
A2

array([[5, 5, 5, 3],
       [5, 5, 1, 5],
       [5, 2, 5, 5]])

### Step B: (12 pts)

In [9]:
# Add the cells for Step B
B1 = np.arange(1, 10)
B1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
BS = np.split(B1, [3, 6])
BS

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [11]:
B2, B3, B4 = np.vsplit(BS, [1,2])

In [12]:
B2

array([[1, 2, 3]])

In [13]:
B3

array([[4, 5, 6]])

In [14]:
B4

array([[7, 8, 9]])

In [15]:
B5 = np.subtract(np.add(np.multiply(4, B4), np.multiply(3, B3)), np.multiply(2, B2))
B5

array([[38, 43, 48]])

In [16]:
np.max(B5)

48

In [17]:
np.min(B5)

38

In [18]:
np.sum(B5)

129

### Step C: (8 pts)

In [19]:
# Add the cells for Step C
C1 = np.arange(1, 20, 2)
C1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
C2 = C1.reshape((5, 2))
C2

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [21]:
C3 = C2.sum(axis=1).reshape((5, 1))
C3

array([[ 4],
       [12],
       [20],
       [28],
       [36]])

In [22]:
C4 = np.hstack([C2, C3])
C4

array([[ 1,  3,  4],
       [ 5,  7, 12],
       [ 9, 11, 20],
       [13, 15, 28],
       [17, 19, 36]])

### Step D: (18 pts)

In [23]:
# Add the cells for Step D
np.random.seed(33)
D = np.random.randint(1, high=9, size=(3,5))

In [24]:
DM = np.median(D)
DM

4.0

In [25]:
DML = np.less(D, DM)
DML

array([[False, False,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False,  True, False]])

In [26]:
np.count_nonzero(DML)

6

In [27]:
DMG = np.greater(D, DM)
DMG

array([[ True,  True, False, False, False],
       [False, False, False,  True,  True],
       [False,  True,  True, False,  True]])

In [28]:
np.count_nonzero(DMG)

7

In [29]:
DME = np.equal(D, DM)
DME

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False, False]])

In [30]:
np.count_nonzero(DME)

2

In [31]:
DMM = np.greater_equal(D, DM - 1) & np.less_equal(D, DM + 1)
DMM

array([[ True, False, False,  True,  True],
       [False, False,  True, False, False],
       [ True, False,  True,  True, False]])

In [32]:
np.count_nonzero(DMM)

7

In [33]:
D15 = np.reshape(D, (1, 15))
D15

array([[5, 8, 1, 3, 3, 2, 2, 4, 7, 6, 4, 7, 5, 3, 6]])

In [34]:
index = np.array([7, 5, 9])
D15[0][index]

array([4, 2, 6])

## Part B: Stock Stats (51 pts)

### Step A: Read the Dataset

In [35]:
# Import the needed libraries

import numpy as np
import csv
from math import sqrt

In [36]:
# Read in the stock data 

def read_stock_info(filename):
    """
    1. Use a try/except block and for loops to read the dataset 
       contained in a CSV file and place it in a nested list.  Open 
       the file with the 'with open as' statement, which does not 
       require that you you explicitly close the file. Use the 
       csv.reader function: See the Working With CSV and JSON Modules 
       pdf file. Each inner list holds the data from the line in the 
       file. Each line is like a record from a database table.
       Each element of the list is a field from a database table.
       Each line is has field names of
       ['Date','Open','High','Low','Close','Volume','Name']
    2. You need to strip all whitespace from the Date and Name fields
       You need to convert the prices (Open,High,Low,Close) to floats: 
       and the Volume to an integer
       Traverse each record of the outer list using a for loop
       Convert each field as specified above
    3. Return the converted nested list  
     """
    try:
        # Using 'with open as' keeps you from having 
        # to explicitly close the file object
        with open(filename, 'r') as input_file:
        
            # See CSV JSON pdf file for more informsation
            # about reading CSV files into a Python program.      
            stock_list = csv.reader(input_file)
            stocks_data = list(stock_list)
            
            # Traverse every row (rec) in the nested stock_data list
            for rec in range(len(stocks_data)):
                # Strip whitespace chars from the first 0) and last(6) fields
                for field in [0,6]:
                    stocks_data[rec][field] = stocks_data[rec][field].strip()
                # Convert the stock prices to floats
                for field in range(1, 5):
                    stocks_data[rec][field] = float(stocks_data[rec][field])
                # Convert the volume to integer   
                stocks_data[rec][5] = int(stocks_data[rec][5]) 
    except IOError:
        print("File Not Found Error.")    
    
    return stocks_data

In [37]:
# Read the stock data file
stocks_data = read_stock_info('4stocks_1qtr.csv')

# Print the first 100 stock records

print("\nFirst 10 stock records")
for rec in stocks_data[:10]:
    print(rec)


First 10 stock records
['1/3/2017', 115.8, 116.33, 114.76, 116.15, 28781865, 'AAPL']
['1/4/2017', 115.85, 116.51, 115.75, 116.02, 21118116, 'AAPL']
['1/5/2017', 115.92, 116.86, 115.81, 116.61, 22193587, 'AAPL']
['1/6/2017', 116.78, 118.16, 116.47, 117.91, 31751900, 'AAPL']
['1/9/2017', 117.95, 119.43, 117.94, 118.99, 33561948, 'AAPL']
['1/10/2017', 118.77, 119.38, 118.3, 119.11, 24462051, 'AAPL']
['1/11/2017', 118.74, 119.93, 118.6, 119.75, 27588593, 'AAPL']
['1/12/2017', 118.9, 119.3, 118.21, 119.25, 27086220, 'AAPL']
['1/13/2017', 119.11, 119.62, 118.81, 119.04, 26111948, 'AAPL']
['1/17/2017', 118.34, 120.24, 118.22, 120.0, 34439843, 'AAPL']


### Step B: Get the Month Number from the Date (4 pts)

In [38]:
# Get the month from the date string
# Using the string index method and string slicing

def get_month(date):
    # Use the string index method to find the first '/' in the string
    slash_index = date.index('/')
    
    # Use slicing to grab the characters before the first slash
    month_str = date[0:slash_index]
    
    # Convert the string to integer
    month = int(month_str)
        
    return month    

In [39]:
# Test the function

date  = '1/3/2017'
month = get_month(date)
month

1

In [40]:
# Get the month number from the date string
# Use the string split method to produce a list
# Convert the first element (index 0) of the list into an integer
# Return the integer

def get_month_num(date):
    
    ## Add your code here ##
    month_num = int(date.split('/')[0])    
    return month_num  

In [41]:
# Test your get_month_num function:
# First, complete the code in the above cell
# Then convert the cell type of this cell here from Raw NBConvert to Code
# Next, run this cell
# The code output should be: 1

date  = '01/03/2017'
month = get_month_num(date)
month

1

### Step C: Calculate Coefficient of Variation (4 pts)

In [42]:
# Calculate the coefficient of variation for the
# given list of values using lists and for loops

def calc_coeff_var(values):
    """
    Calculates the standard deviation from the mean for a list of values
    """
    mean = sum(values) / len(values)
    
    diffs = []
    for x in values:
        diffs.append(x - mean)
        
    squ_diffs = []
    for d in diffs:
        squ_diffs.append(d**2)

    std_dev = sqrt(sum(squ_diffs) / len(values))
    coeff_var = std_dev / mean
    
    return coeff_var

In [43]:
# Test the function

values = [115.8, 116.33, 114.76, 116.15]
calc_coeff_var(values)

0.005252146568184989

In [44]:
# Calculate the coefficient of variation 
# for the given list of values using the given mean

def calc_coeff_var_lc(values):
    """
    Calculates the standard deviation from the mean for a list of values
    Here is the coversion from the calc_coeff_var function
    to the calc_coeff_var_lc function: It is a many step process    
    
    #1.
    mean = sum(values) / len(values)
    diffs = []
    for x in values:
        diffs.append(x - mean)
    
    Becomes
    
    mean = sum(values) / len(values)
    diffs = [x - mean for x in values]
        
    #2. 
    squ_diffs = []
    for d in diffs:
        squ_diffs.append(d**2)
    
    Becomes
    
    squ_diffs = [d**2 for d in diffs] 
    
    #3. 
    Putting #1 and #2 together: 
    diffs = [x - mean for x in values]
    squ_diffs = [d**2 for d in diffs]
    
    Becomes
    
    squ_diffs = [d**2 for d in [x - mean for x in values]]
        
    #4. 
    Putting std_dev with #3 together: 
    
    std_dev = sqrt(sum(squ_diffs) / len(values))
    squ_diffs = [d**2 for d in [x - mean for x in values]]
    
    Becomes
     
    std_dev = sqrt(sum([d ** 2 for d in [x - mean for x in values]]) / len(values)) 
    
    #5.
    Change sum function argument to a generator expression: becomes
     
    std_dev = sqrt(sum(d ** 2 for d in [x - mean for x in values]) / len(values))
    
    #6.
    Putting coeff_var with #5 together:
    
    coeff_var = std_dev / mean 
    # becomes
    """
    mean = sum(values) / len(values)
    coeff_var = sqrt(sum(d ** 2 for d in [x - mean for x in values]) / len(values)) / mean
    return coeff_var

In [45]:
# Test the function

values = [115.8, 116.33, 114.76, 116.15]
calc_coeff_var_lc(values)

0.005252146568184989

In [46]:
# Calculate the coefficient of variation for the
# given list of values using just NumPy constructs
# This can be done with one line of code

def calc_coeff_var_np(values):
    
    ## Add your code here ##
    coeff_var = np.std(values) / np.mean(values)
    
    return coeff_var

In [47]:
# Test your calc_coeff_var_np function:
# First, complete the code in the above cell
# Then convert the cell type of this cell here from Raw NBConvert to Code
# Next, run this cell
# The code output should be the same output as in the 
# calc_coeff_var and calc_coeff_var_lc fyunctions

values = [115.8, 116.33, 114.76, 116.15]
calc_coeff_var_np(values)

0.005252146568184989

### Step D: Modify the Stocks Data Nested List (4 pts)

In [48]:
# rec: ['Date', Open, High, Low, Close, Volume, 'Name']
# Replace the 'Date' Field with the 'Month' field
# Add the 'CoeffVar' Field before the 'Volume' field
# New rec: [Month, Open, High, Low, Close, 
#           CoeffVar, Volume, 'Name']

def modify_stocks_data(stocks_data):    
        
    ## Add your code here ##
    for rec in stocks_data:
        rec[0] = get_month(rec[0])
        rec.insert(5, calc_coeff_var_np(rec[1:5]))
    
    return stocks_data

In [49]:
# Test your modify_stocks_data function:
# First, note the output from the second cell of this Step D
#        it is in the third cell in this Step in Raw NBConvert format
# Then complete the code in the above cell 
# Next, convert the cell type of this cell here from Raw NBConvert to Code
# Then run this cell
# Make sure your output matches the modify_stocks function output
# You will get an error, if you run both modify_stocks and modify_stocks_data

stocks_data = modify_stocks_data(stocks_data)

# Print the first 10 stock records

print("\nFirst 10 stock records")
for rec in stocks_data[:10]:
    print(rec)


First 10 stock records
[1, 115.8, 116.33, 114.76, 116.15, 0.005252146568184989, 28781865, 'AAPL']
[1, 115.85, 116.51, 115.75, 116.02, 0.002517344148881291, 21118116, 'AAPL']
[1, 115.92, 116.86, 115.81, 116.61, 0.003831380027370804, 22193587, 'AAPL']
[1, 116.78, 118.16, 116.47, 117.91, 0.00612735707247605, 31751900, 'AAPL']
[1, 117.95, 119.43, 117.94, 118.99, 0.005493109197945443, 33561948, 'AAPL']
[1, 118.77, 119.38, 118.3, 119.11, 0.0033932446385641015, 24462051, 'AAPL']
[1, 118.74, 119.93, 118.6, 119.75, 0.004951821084933229, 27588593, 'AAPL']
[1, 118.9, 119.3, 118.21, 119.25, 0.0036600077731633075, 27086220, 'AAPL']
[1, 119.11, 119.62, 118.81, 119.04, 0.002483077291113693, 26111948, 'AAPL']
[1, 118.34, 120.24, 118.22, 120.0, 0.007759046731390498, 34439843, 'AAPL']


### Step E: Create Sorted Stock List (7 pts)

In [50]:
# Create a unique list of the stock names by extracting
# the names from the last field in each record and 
# placing them in a list using a list comprehension. 
# Next, the NumPy unique function is used to create 
# a NumPy array of sorted unique names from the list.
# The NumPy array is then converted into a list

def get_sorted_stock_list_np(stocks_data):
   
    stock_list = [rec[-1] for rec in stocks_data]
    stock_list = list(np.unique(stock_list))
    return stock_list

In [51]:
# Print the sorted stock names

stock_list = get_sorted_stock_list_np(stocks_data)

print("\nSorted Stock List\n")
print(stock_list) 


Sorted Stock List

['AAPL', 'GOOGL', 'IBM', 'ORCL']


In [52]:
# Create a unique list of the stock names by extracting
# the names from the last field in each record and 
# placing them in a set.
# The set will store only unique values
# Convert the set to a list and sort the list

def get_sorted_stock_list(stocks_data):
    """  
    Creates a sorted list of stock names    
    """
    stock_set = set()
    for rec in stocks_data:
        stock_set.add(rec[-1])
    
    stock_list = list(stock_set)    
    stock_list.sort()        
    return stock_list

In [53]:
# Print the sorted stock names

stock_list = get_sorted_stock_list(stocks_data)

print("\nSorted Stock List\n")
print(stock_list)


Sorted Stock List

['AAPL', 'GOOGL', 'IBM', 'ORCL']


In [54]:
# Create a unique list of the stock names by extracting
# the names from the last field in each record and 
# placing them in a set using a set comprehension.
# The set will store only unique values
# Convert the set to a list and sort the list

def get_sorted_stock_list_sc(stocks_data):
    
    ## Add your code here ##
    stock_list = list({rec[-1] for rec in stocks_data})
    stock_list.sort()
    return stock_list

In [55]:
# Test your get_sorted_stock_list_sc function and print the sorted stock names
# First, note the output from running the get_sorted_stock_list_np function
# or the get_sorted_stock_list function
# Then complete the code in the above cell 
# Next, convert the cell type of this cell here from Raw NBConvert to Code
# Then run this cell
# Make sure your output matches the get_sorted_stock_list_np function
# and the get_sorted_stock_list function output

stock_list = get_sorted_stock_list_sc(stocks_data)

print("\nSorted Stock List\n")
print(stock_list)  


Sorted Stock List

['AAPL', 'GOOGL', 'IBM', 'ORCL']


### Step F: Extract Only One Stock from the Nested List (7 pts)

In [56]:
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume, 'Name']
#
# Extract from the stocks_data nested list only 
# those records pertaining to a particular stock
# Use for loops 
# Remove the stock Name from the record appending only the first seven fields
# 
# New Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]

def extract_stock(stocks_data, stock):    
    stock_data = []    
    for rec in stocks_data:
        if rec[-1] == stock:
            stock_data.append(rec[:-1])
    
    return stock_data

In [57]:
# Extract the particular stock data

stock = 'AAPL'
print("Stock Data For", stock)
stock_data = extract_stock(stocks_data, stock)

# Print ten records

print("\nFirst 10 stock records")
for rec in stock_data[:10]:
    print(rec)

Stock Data For AAPL

First 10 stock records
[1, 115.8, 116.33, 114.76, 116.15, 0.005252146568184989, 28781865]
[1, 115.85, 116.51, 115.75, 116.02, 0.002517344148881291, 21118116]
[1, 115.92, 116.86, 115.81, 116.61, 0.003831380027370804, 22193587]
[1, 116.78, 118.16, 116.47, 117.91, 0.00612735707247605, 31751900]
[1, 117.95, 119.43, 117.94, 118.99, 0.005493109197945443, 33561948]
[1, 118.77, 119.38, 118.3, 119.11, 0.0033932446385641015, 24462051]
[1, 118.74, 119.93, 118.6, 119.75, 0.004951821084933229, 27588593]
[1, 118.9, 119.3, 118.21, 119.25, 0.0036600077731633075, 27086220]
[1, 119.11, 119.62, 118.81, 119.04, 0.002483077291113693, 26111948]
[1, 118.34, 120.24, 118.22, 120.0, 0.007759046731390498, 34439843]


In [58]:
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume, 'Name']
#
# Extract from the stocks_data nested list only 
# those records pertaining to a particular stock
# Use a list comprehension 
# Remove the stock Name from the record appending only the first seven fields
# 
# New Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]

def extract_stock_lc(stocks_data, stock):
       
    ## Add your code here ##
    stock_data = [rec[:-1] for rec in stocks_data if rec[-1] == stock]
    
    return stock_data

In [59]:
# Test your extract_stock_lc function:
# First, note the output from the extract_stock function
# Then complete the code in the above cell 
# Next, convert the cell type of this cell here from Raw NBConvert to Code
# Then run this cell
# Make sure your output matches the extract_stock function output

stock = 'AAPL'
print("Stock Data For", stock)
stock_data = extract_stock_lc(stocks_data, stock)

# Print ten records

print("\nFirst 10 stock records")
for rec in stock_data[:10]:
    print(rec)                                                                                                              

Stock Data For AAPL

First 10 stock records
[1, 115.8, 116.33, 114.76, 116.15, 0.005252146568184989, 28781865]
[1, 115.85, 116.51, 115.75, 116.02, 0.002517344148881291, 21118116]
[1, 115.92, 116.86, 115.81, 116.61, 0.003831380027370804, 22193587]
[1, 116.78, 118.16, 116.47, 117.91, 0.00612735707247605, 31751900]
[1, 117.95, 119.43, 117.94, 118.99, 0.005493109197945443, 33561948]
[1, 118.77, 119.38, 118.3, 119.11, 0.0033932446385641015, 24462051]
[1, 118.74, 119.93, 118.6, 119.75, 0.004951821084933229, 27588593]
[1, 118.9, 119.3, 118.21, 119.25, 0.0036600077731633075, 27086220]
[1, 119.11, 119.62, 118.81, 119.04, 0.002483077291113693, 26111948]
[1, 118.34, 120.24, 118.22, 120.0, 0.007759046731390498, 34439843]


### Step G: Extract Only One Month from the Stock Nested List (7 pts)

In [60]:
# Extract from the stock_data nested list for the particular stock
# only those records pertaining to a particular month, 
# This uses a list comprehension
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]

def extract_month_lc(stock_data, month): 
    
    stock_mon_data = [rec for rec in stock_data if rec[0] == month]    
    
    return stock_mon_data

In [61]:
# Test the function
# Extract the particular stock month data

month = 1
stock_mon_data = extract_month_lc(stock_data, month)

# Print ten records
print ("\nFirst 10 stock records")
for rec in stock_mon_data[:10]:
    print(rec)


First 10 stock records
[1, 115.8, 116.33, 114.76, 116.15, 0.005252146568184989, 28781865]
[1, 115.85, 116.51, 115.75, 116.02, 0.002517344148881291, 21118116]
[1, 115.92, 116.86, 115.81, 116.61, 0.003831380027370804, 22193587]
[1, 116.78, 118.16, 116.47, 117.91, 0.00612735707247605, 31751900]
[1, 117.95, 119.43, 117.94, 118.99, 0.005493109197945443, 33561948]
[1, 118.77, 119.38, 118.3, 119.11, 0.0033932446385641015, 24462051]
[1, 118.74, 119.93, 118.6, 119.75, 0.004951821084933229, 27588593]
[1, 118.9, 119.3, 118.21, 119.25, 0.0036600077731633075, 27086220]
[1, 119.11, 119.62, 118.81, 119.04, 0.002483077291113693, 26111948]
[1, 118.34, 120.24, 118.22, 120.0, 0.007759046731390498, 34439843]


In [62]:
# Extract from the stock_data nested list for the particular stock
# only those records pertaining to a particular month, 
# using lists and for loops
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]

def extract_month(stock_data, month):
            
    ## Add your code here ##
    stock_mon_data = []
    for rec in stock_data:
        if month == rec[0]:
            stock_mon_data.append(rec)
    
    return stock_mon_data

In [63]:
# Test your extract_month function:
# First, note the output from the extract_month_lc function
# Then complete the code in the above cell 
# Next, convert the cell type of this cell here from Raw NBConvert to Code
# Then run this cell
# Make sure your output matches the extract_month_lc function output

month = 1
stock_mon_data = extract_month(stock_data, month)

# Print ten records
print("\nFirst 10 stock records")
for rec in stock_mon_data[:10]:
    print(rec)


First 10 stock records
[1, 115.8, 116.33, 114.76, 116.15, 0.005252146568184989, 28781865]
[1, 115.85, 116.51, 115.75, 116.02, 0.002517344148881291, 21118116]
[1, 115.92, 116.86, 115.81, 116.61, 0.003831380027370804, 22193587]
[1, 116.78, 118.16, 116.47, 117.91, 0.00612735707247605, 31751900]
[1, 117.95, 119.43, 117.94, 118.99, 0.005493109197945443, 33561948]
[1, 118.77, 119.38, 118.3, 119.11, 0.0033932446385641015, 24462051]
[1, 118.74, 119.93, 118.6, 119.75, 0.004951821084933229, 27588593]
[1, 118.9, 119.3, 118.21, 119.25, 0.0036600077731633075, 27086220]
[1, 119.11, 119.62, 118.81, 119.04, 0.002483077291113693, 26111948]
[1, 118.34, 120.24, 118.22, 120.0, 0.007759046731390498, 34439843]


### Step H: Calculate the Stock Statistics and Place in Nested List (6 pts)

In [64]:
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]
# Calculate the stock stats for each stock 
# and place them in a nested list:
# This function uses the provided code
# ['Name', JanPerf, JanVol, FebPerf, FebVol, MarPerf, MarVol, QtrPerf, QtrVol]

def calc_stock_stats(stocks_data):
    stocks_stats = []
    
    # Get Sorted Stock List
    stock_list = get_sorted_stock_list_np(stocks_data)
    
    # Traverse Stock List ['AAPL', 'GOOGL', IBM', 'ORCL'] to 
    # Extract All Stock Rows
    for stock in stock_list:
        
        stock_stats = []
        
        # Build Stock_Stats inner list
        stock_stats.append(stock)
        
        # Get All Rows Pertaining to a Certain Stock
        stock_data = extract_stock(stocks_data, stock)
        
        # Convert the Nested List into a NumPy Array
        qtr_array = np.array(stock_data)
        
        # Calculate Stock Volatility For Quarter
        # Grab the CoeffVar column for the stock
        # All rows and sixth column
        cov_col = qtr_array[:, 5]
        
        # Find the average of the CoeffVar column
        qtr_volatility = np.mean(cov_col) 
        
        # Calculate the Quarter Performance For the Stock
        # Get the index of the last row in CoeffVar column
        last_row = cov_col.size - 1
        
        # Get the price of the stock at the start of the quarter
        # First row and second column 
        open_qtr = qtr_array[0, 1]
        
        # Get the price of the stock at the end of the quarter
        # Last row and fifth column 
        close_qtr = qtr_array[last_row, 4]
        
        # Calculate the stock performance for the quarter
        qtr_perf = (close_qtr - open_qtr) / open_qtr
            
        # For Each Month in the Quarter
        for month in range(1,4):
            
            # Get All Rows Pertaining to a Certain Stock and Month
            stock_mon_data = extract_month_lc(stock_data, month)
            
            # Convert the Nested List into a NumPy Array
            month_array = np.array(stock_mon_data)
            
            # Calculate Stock Volatility For Month
            # Grab the CoeffVar column for the stock
            # All rows and sixth column
            cov_col = month_array[:, 5]
            
            # Find the average of the CoeffVar column
            mon_volatility = np.mean(cov_col)     
            
            # Calculate the Month Performance For the Stock
            # Get the index of the last row in CoeffVar column
            last_row = cov_col.size - 1
            
            # Get the price of the stock at the start of the month
            # First row and second column
            open_mon = month_array[0, 1]
            
            # Get the price of the stock at the end of the month
            # Last row and fifth column
            close_mon = month_array[last_row, 4]
            
            # Calculate the stock performance for the month
            mon_perf = (close_mon - open_mon) / open_mon
            
            # Build Stock_Stats month inner list
            stock_stats.append(mon_perf)
            stock_stats.append(mon_volatility)
            
        # Build Stock_Stats quarter inner list
        stock_stats.append(qtr_perf)
        stock_stats.append(qtr_volatility)
        
        # Build Stock_Stats nested list
        stocks_stats.append(stock_stats)
        
    return stocks_stats        

In [65]:
# Run the function to produce the stock_stats nested list
stock_stats = calc_stock_stats(stocks_data)

print("\nStock records")
for rec in stock_stats:
    print(rec)
    print()


Stock records
['AAPL', 0.04792746113989635, 0.0038063818372243824, 0.07840667558844373, 0.004104691494182056, 0.04184494887228959, 0.004449168670230453, 0.24058721934369603, 0.004136252492729792]

['GOOGL', 0.024443556243911032, 0.0050996002450909295, 0.025400485436893144, 0.003520094170776388, -0.004204937865582984, 0.004200463279050654, 0.05892932976942863, 0.004282007251044113]

['IBM', 0.04502994011976054, 0.005821552290947118, 0.027542857142857105, 0.004091956342038601, -0.0351285460992908, 0.004011643526433857, 0.04275449101796399, 0.004620097055252492]

['ORCL', 0.04317295188556558, 0.0047110415421785954, 0.058925907508702254, 0.004716111192834354, 0.043508771929824545, 0.004378410004049176, 0.1602080624187255, 0.004589199574202511]



In [66]:
# Rec: [Month, Open, High, Low, Close, CoeffVar, Volume]

# Calculate the stock stats for each stock 
# and place them in a nested list:
# This function uses the code that you were required to write
# It is identical to calc_stock_stats, except for the replacement of some of the function calls

# ['Name', JanPerf, JanVol, FebPerf, FebVol, MarPerf, MarVol, QtrPerf, QtrVol]

def calc_stock_stats_new(stocks_data):
    stocks_stats = []
    
    stock_list = get_sorted_stock_list_sc(stocks_data)

    for stock in stock_list:
        
        stock_stats = []
        
        stock_stats.append(stock)
        
        stock_data = extract_stock_lc(stocks_data, stock)
        
        qtr_array = np.array(stock_data)

        cov_col = qtr_array[:, 5]
        
        qtr_volatility = np.mean(cov_col) 
        
        last_row = cov_col.size - 1
        
        open_qtr = qtr_array[0, 1]

        close_qtr = qtr_array[last_row, 4]

        qtr_perf = (close_qtr - open_qtr) / open_qtr

        for month in range(1,4):
            
            stock_mon_data = extract_month(stock_data, month)
            
            month_array = np.array(stock_mon_data)
            
            cov_col = month_array[:, 5]

            mon_volatility = np.mean(cov_col)         

            last_row = cov_col.size - 1
            
            open_mon = month_array[0, 1]

            close_mon = month_array[last_row, 4]
            
            mon_perf = (close_mon - open_mon) / open_mon

            stock_stats.append(mon_perf)
            stock_stats.append(mon_volatility)

        stock_stats.append(qtr_perf)
        stock_stats.append(qtr_volatility)

        stocks_stats.append(stock_stats)
        
    return stocks_stats          

In [67]:
# Test your calc_stock_stats_new function:
# First, note the output from the calc_stock_stats function
# Then complete the code in the above cell 
# Next, convert the cell type of this cell here from Raw NBConvert to Code
# Then run this cell
# Make sure your output matches the calc_stock_stats function output

stock_stats = calc_stock_stats_new(stocks_data)
print("\nStock records")
for rec in stock_stats:
    print(rec)
    print()


Stock records
['AAPL', 0.04792746113989635, 0.0038063818372243824, 0.07840667558844373, 0.004104691494182056, 0.04184494887228959, 0.004449168670230453, 0.24058721934369603, 0.004136252492729792]

['GOOGL', 0.024443556243911032, 0.0050996002450909295, 0.025400485436893144, 0.003520094170776388, -0.004204937865582984, 0.004200463279050654, 0.05892932976942863, 0.004282007251044113]

['IBM', 0.04502994011976054, 0.005821552290947118, 0.027542857142857105, 0.004091956342038601, -0.0351285460992908, 0.004011643526433857, 0.04275449101796399, 0.004620097055252492]

['ORCL', 0.04317295188556558, 0.0047110415421785954, 0.058925907508702254, 0.004716111192834354, 0.043508771929824545, 0.004378410004049176, 0.1602080624187255, 0.004589199574202511]



### Step I: Print the Stock Statistics

In [68]:
# Print the stock stats for each stock 
# ['Name', JanPerf, JanVol, FebPerf, FebVol, 
#          MarPerf, MarVol, QtrPerf, QtrVol]

def print_stock_stats(stock_stats):
    for stock in stock_stats:
        print("Statistics For", stock[0])
        print("Jan Perfomance", '{:6.4f}'.format(stock[1]), 
              "Jan Volatility", '{:8.6f}'.format(stock[2]))
        print("Feb Perfomance", '{:6.4f}'.format(stock[3]), 
              "Feb Volatility", '{:8.6f}'.format(stock[4]))
        print("Mar Perfomance", '{:6.4f}'.format(stock[5]), 
              "Mar Volatility", '{:8.6f}'.format(stock[6]))
        print("1st Qtr Perfomance", '{:6.4f}'.format(stock[7]), 
              "1st Qtr Volatility", '{:8.6f}'.format(stock[8]))
        print()

In [69]:
# Print the Stock Statistics for comparison

print_stock_stats (stock_stats)

Statistics For AAPL
Jan Perfomance 0.0479 Jan Volatility 0.003806
Feb Perfomance 0.0784 Feb Volatility 0.004105
Mar Perfomance 0.0418 Mar Volatility 0.004449
1st Qtr Perfomance 0.2406 1st Qtr Volatility 0.004136

Statistics For GOOGL
Jan Perfomance 0.0244 Jan Volatility 0.005100
Feb Perfomance 0.0254 Feb Volatility 0.003520
Mar Perfomance -0.0042 Mar Volatility 0.004200
1st Qtr Perfomance 0.0589 1st Qtr Volatility 0.004282

Statistics For IBM
Jan Perfomance 0.0450 Jan Volatility 0.005822
Feb Perfomance 0.0275 Feb Volatility 0.004092
Mar Perfomance -0.0351 Mar Volatility 0.004012
1st Qtr Perfomance 0.0428 1st Qtr Volatility 0.004620

Statistics For ORCL
Jan Perfomance 0.0432 Jan Volatility 0.004711
Feb Perfomance 0.0589 Feb Volatility 0.004716
Mar Perfomance 0.0435 Mar Volatility 0.004378
1st Qtr Perfomance 0.1602 1st Qtr Volatility 0.004589



### Step J: Fill in Table With Stock Name (12 pts)